non_openjdk_javadoc_files := \
  luni/src/main/java/android/system/ErrnoException.java \
  luni/src/main/java/android/system/GaiException.java \
  luni/src/main/java/android/system/NetlinkSocketAddress.java \
  luni/src/main/java/android/system/Os.java \
  luni/src/main/java/android/system/OsConstants.java \
  luni/src/main/java/android/system/PacketSocketAddress.java \
  luni/src/main/java/android/system/StructAddrinfo.java \
  luni/src/main/java/android/system/StructFlock.java \
  luni/src/main/java/android/system/StructGroupReq.java \
  luni/src/main/java/android/system/StructGroupSourceReq.java \
  luni/src/main/java/android/system/StructLinger.java \
  luni/src/main/java/android/system/StructPasswd.java \
  luni/src/main/java/android/system/StructPollfd.java \
  luni/src/main/java/android/system/StructStat.java \
  luni/src/main/java/android/system/StructStatVfs.java \
  luni/src/main/java/android/system/StructTimeval.java \
  luni/src/main/java/android/system/StructUcred.java \
  luni/src/main/java/android/system/StructUtsname.java \
  luni/src/main/java/android/util/MutableBoolean.java \
  luni/src/main/java/android/util/MutableByte.java \
  luni/src/main/java/android/util/MutableChar.java \
  luni/src/main/java/android/util/MutableDouble.java \
  luni/src/main/java/android/util/MutableFloat.java \
  luni/src/main/java/android/util/MutableInt.java \
  luni/src/main/java/android/util/MutableLong.java \
  luni/src/main/java/android/util/MutableShort.java \
  dalvik/src/main/java/dalvik/annotation/AnnotationDefault.java \
  dalvik/src/main/java/dalvik/annotation/EnclosingClass.java \
  dalvik/src/main/java/dalvik/annotation/EnclosingMethod.java \
  dalvik/src/main/java/dalvik/annotation/InnerClass.java \
  dalvik/src/main/java/dalvik/annotation/KnownFailure.java \
  dalvik/src/main/java/dalvik/annotation/MemberClasses.java \
  dalvik/src/main/java/dalvik/annotation/Signature.java \
  dalvik/src/main/java/dalvik/annotation/TestTarget.java \
  dalvik/src/main/java/dalvik/annotation/TestTargetClass.java \
  dalvik/src/main/java/dalvik/annotation/Throws.java \
  dalvik/src/main/java/dalvik/bytecode/OpcodeInfo.java \
  dalvik/src/main/java/dalvik/bytecode/Opcodes.java \
  dalvik/src/main/java/dalvik/system/AllocationLimitError.java \
  dalvik/src/main/java/dalvik/system/BaseDexClassLoader.java \
  dalvik/src/main/java/dalvik/system/BlockGuard.java \
  dalvik/src/main/java/dalvik/system/CloseGuard.java \
  dalvik/src/main/java/dalvik/system/DalvikLogHandler.java \
  dalvik/src/main/java/dalvik/system/DalvikLogging.java \
  dalvik/src/main/java/dalvik/system/DexClassLoader.java \
  dalvik/src/main/java/dalvik/system/DexFile.java \
  dalvik/src/main/java/dalvik/system/DexPathList.java \
  dalvik/src/main/java/dalvik/system/NativeStart.java \
  dalvik/src/main/java/dalvik/system/PathClassLoader.java \
  dalvik/src/main/java/dalvik/system/PotentialDeadlockError.java \
  dalvik/src/main/java/dalvik/system/SocketTagger.java \
  dalvik/src/main/java/dalvik/system/TemporaryDirectory.java \
  dalvik/src/main/java/dalvik/system/VMDebug.java \
  libart/src/main/java/dalvik/system/VMRuntime.java \
  libart/src/main/java/dalvik/system/VMStack.java \
  libart/src/main/java/dalvik/system/TransactionAbortError.java \
  dalvik/src/main/java/dalvik/system/ZygoteHooks.java \
  libart/src/main/java/java/lang/Daemons.java \
  libart/src/main/java/java/lang/DexCache.java \
  luni/src/main/java/java/lang/FindBugsSuppressWarnings.java \
  libart/src/main/java/java/lang/VMClassLoader.java \
  luni/src/main/java/java/lang/ref/FinalizerReference.java \
  libart/src/main/java/java/lang/reflect/AbstractMethod.java \
  luni/src/main/java/java/math/BigDecimal.java \
  luni/src/main/java/java/math/BigInt.java \
  luni/src/main/java/java/math/BigInteger.java \
  luni/src/main/java/java/math/BitLevel.java \
  luni/src/main/java/java/math/Conversion.java \
  luni/src/main/java/java/math/Division.java \
  luni/src/main/java/java/math/Logical.java \
  luni/src/main/java/java/math/MathContext.java \
  luni/src/main/java/java/math/Multiplication.java \
  luni/src/main/java/java/math/NativeBN.java \
  luni/src/main/java/java/math/Primality.java \
  luni/src/main/java/java/math/RoundingMode.java \
  luni/src/main/java/java/net/DefaultFileNameMap.java \
  luni/src/main/java/java/nio/NIOAccess.java \
  luni/src/main/java/java/nio/NioUtils.java \
  luni/src/main/java/java/nio/charset/CharsetDecoderICU.java \
  luni/src/main/java/java/nio/charset/CharsetEncoderICU.java \
  luni/src/main/java/java/nio/charset/CharsetICU.java \
  luni/src/main/java/java/nio/charset/ModifiedUtf8.java \
  luni/src/main/java/java/util/concurrent/AbstractExecutorService.java \
  luni/src/main/java/java/util/concurrent/ArrayBlockingQueue.java \
  luni/src/main/java/java/util/concurrent/BlockingDeque.java \
  luni/src/main/java/java/util/concurrent/BlockingQueue.java \
  luni/src/main/java/java/util/concurrent/BrokenBarrierException.java \
  luni/src/main/java/java/util/concurrent/Callable.java \
  luni/src/main/java/java/util/concurrent/CancellationException.java \
  luni/src/main/java/java/util/concurrent/CompletableFuture.java \
  luni/src/main/java/java/util/concurrent/CompletionException.java \
  luni/src/main/java/java/util/concurrent/CompletionService.java \
  luni/src/main/java/java/util/concurrent/CompletionStage.java \
  luni/src/main/java/java/util/concurrent/ConcurrentHashMap.java \
  luni/src/main/java/java/util/concurrent/ConcurrentLinkedDeque.java \
  luni/src/main/java/java/util/concurrent/ConcurrentLinkedQueue.java \
  luni/src/main/java/java/util/concurrent/ConcurrentMap.java \
  luni/src/main/java/java/util/concurrent/ConcurrentNavigableMap.java \
  luni/src/main/java/java/util/concurrent/ConcurrentSkipListMap.java \
  luni/src/main/java/java/util/concurrent/ConcurrentSkipListSet.java \
  luni/src/main/java/java/util/concurrent/CopyOnWriteArrayList.java \
  luni/src/main/java/java/util/concurrent/CopyOnWriteArraySet.java \
  luni/src/main/java/java/util/concurrent/CountDownLatch.java \
  luni/src/main/java/java/util/concurrent/CountedCompleter.java \
  luni/src/main/java/java/util/concurrent/CyclicBarrier.java \
  luni/src/main/java/java/util/concurrent/DelayQueue.java \
  luni/src/main/java/java/util/concurrent/Delayed.java \
  luni/src/main/java/java/util/concurrent/Exchanger.java \
  luni/src/main/java/java/util/concurrent/ExecutionException.java \
  luni/src/main/java/java/util/concurrent/Executor.java \
  luni/src/main/java/java/util/concurrent/ExecutorCompletionService.java \
  luni/src/main/java/java/util/concurrent/ExecutorService.java \
  luni/src/main/java/java/util/concurrent/Executors.java \
  luni/src/main/java/java/util/concurrent/ForkJoinPool.java \
  luni/src/main/java/java/util/concurrent/ForkJoinTask.java \
  luni/src/main/java/java/util/concurrent/ForkJoinWorkerThread.java \
  luni/src/main/java/java/util/concurrent/Future.java \
  luni/src/main/java/java/util/concurrent/FutureTask.java \
  luni/src/main/java/java/util/concurrent/Helpers.java \
  luni/src/main/java/java/util/concurrent/LinkedBlockingDeque.java \
  luni/src/main/java/java/util/concurrent/LinkedBlockingQueue.java \
  luni/src/main/java/java/util/concurrent/LinkedTransferQueue.java \
  luni/src/main/java/java/util/concurrent/Phaser.java \
  luni/src/main/java/java/util/concurrent/PriorityBlockingQueue.java \
  luni/src/main/java/java/util/concurrent/RecursiveAction.java \
  luni/src/main/java/java/util/concurrent/RecursiveTask.java \
  luni/src/main/java/java/util/concurrent/RejectedExecutionException.java \
  luni/src/main/java/java/util/concurrent/RejectedExecutionHandler.java \
  luni/src/main/java/java/util/concurrent/RunnableFuture.java \
  luni/src/main/java/java/util/concurrent/RunnableScheduledFuture.java \
  luni/src/main/java/java/util/concurrent/ScheduledExecutorService.java \
  luni/src/main/java/java/util/concurrent/ScheduledFuture.java \
  luni/src/main/java/java/util/concurrent/ScheduledThreadPoolExecutor.java \
  luni/src/main/java/java/util/concurrent/Semaphore.java \
  luni/src/main/java/java/util/concurrent/SynchronousQueue.java \
  luni/src/main/java/java/util/concurrent/ThreadFactory.java \
  luni/src/main/java/java/util/concurrent/ThreadLocalRandom.java \
  luni/src/main/java/java/util/concurrent/ThreadPoolExecutor.java \
  luni/src/main/java/java/util/concurrent/TimeUnit.java \
  luni/src/main/java/java/util/concurrent/TimeoutException.java \
  luni/src/main/java/java/util/concurrent/TransferQueue.java \
  luni/src/main/java/java/util/concurrent/atomic/AtomicBoolean.java \
  luni/src/main/java/java/util/concurrent/atomic/AtomicInteger.java \
  luni/src/main/java/java/util/concurrent/atomic/AtomicIntegerArray.java \
  luni/src/main/java/java/util/concurrent/atomic/AtomicIntegerFieldUpdater.java \
  luni/src/main/java/java/util/concurrent/atomic/AtomicLong.java \
  luni/src/main/java/java/util/concurrent/atomic/AtomicLongArray.java \
  luni/src/main/java/java/util/concurrent/atomic/AtomicLongFieldUpdater.java \
  luni/src/main/java/java/util/concurrent/atomic/AtomicMarkableReference.java \
  luni/src/main/java/java/util/concurrent/atomic/AtomicReference.java \
  luni/src/main/java/java/util/concurrent/atomic/AtomicReferenceArray.java \
  luni/src/main/java/java/util/concurrent/atomic/AtomicReferenceFieldUpdater.java \
  luni/src/main/java/java/util/concurrent/atomic/AtomicStampedReference.java \
  luni/src/main/java/java/util/concurrent/atomic/DoubleAccumulator.java \
  luni/src/main/java/java/util/concurrent/atomic/DoubleAdder.java \
  luni/src/main/java/java/util/concurrent/atomic/LongAccumulator.java \
  luni/src/main/java/java/util/concurrent/atomic/LongAdder.java \
  luni/src/main/java/java/util/concurrent/atomic/Striped64.java \
  luni/src/main/java/java/util/concurrent/atomic/package-info.java \
  luni/src/main/java/java/util/concurrent/locks/AbstractOwnableSynchronizer.java \
  luni/src/main/java/java/util/concurrent/locks/AbstractQueuedLongSynchronizer.java \
  luni/src/main/java/java/util/concurrent/locks/AbstractQueuedSynchronizer.java \
  luni/src/main/java/java/util/concurrent/locks/Condition.java \
  luni/src/main/java/java/util/concurrent/locks/Lock.java \
  luni/src/main/java/java/util/concurrent/locks/LockSupport.java \
  luni/src/main/java/java/util/concurrent/locks/ReadWriteLock.java \
  luni/src/main/java/java/util/concurrent/locks/ReentrantLock.java \
  luni/src/main/java/java/util/concurrent/locks/ReentrantReadWriteLock.java \
  luni/src/main/java/java/util/concurrent/locks/StampedLock.java \
  luni/src/main/java/java/util/concurrent/locks/package-info.java \
  luni/src/main/java/java/util/concurrent/package-info.java \
  luni/src/main/java/javax/xml/XMLConstants.java \
  luni/src/main/java/javax/xml/datatype/DatatypeConfigurationException.java \
  luni/src/main/java/javax/xml/datatype/DatatypeConstants.java \
  luni/src/main/java/javax/xml/datatype/DatatypeFactory.java \
  luni/src/main/java/javax/xml/datatype/Duration.java \
  luni/src/main/java/javax/xml/datatype/FactoryFinder.java \
  luni/src/main/java/javax/xml/datatype/XMLGregorianCalendar.java \
  luni/src/main/java/javax/xml/namespace/NamespaceContext.java \
  luni/src/main/java/javax/xml/namespace/QName.java \
  luni/src/main/java/javax/xml/parsers/DocumentBuilder.java \
  luni/src/main/java/javax/xml/parsers/DocumentBuilderFactory.java \
  luni/src/main/java/javax/xml/parsers/FactoryConfigurationError.java \
  luni/src/main/java/javax/xml/parsers/FilePathToURI.java \
  luni/src/main/java/javax/xml/parsers/ParserConfigurationException.java \
  luni/src/main/java/javax/xml/parsers/SAXParser.java \
  luni/src/main/java/javax/xml/parsers/SAXParserFactory.java \
  luni/src/main/java/javax/xml/transform/ErrorListener.java \
  luni/src/main/java/javax/xml/transform/OutputKeys.java \
  luni/src/main/java/javax/xml/transform/Result.java \
  luni/src/main/java/javax/xml/transform/Source.java \
  luni/src/main/java/javax/xml/transform/SourceLocator.java \
  luni/src/main/java/javax/xml/transform/Templates.java \
  luni/src/main/java/javax/xml/transform/Transformer.java \
  luni/src/main/java/javax/xml/transform/TransformerConfigurationException.java \
  luni/src/main/java/javax/xml/transform/TransformerException.java \
  luni/src/main/java/javax/xml/transform/TransformerFactory.java \
  luni/src/main/java/javax/xml/transform/TransformerFactoryConfigurationError.java \
  luni/src/main/java/javax/xml/transform/URIResolver.java \
  luni/src/main/java/javax/xml/transform/dom/DOMLocator.java \
  luni/src/main/java/javax/xml/transform/dom/DOMResult.java \
  luni/src/main/java/javax/xml/transform/dom/DOMSource.java \
  luni/src/main/java/javax/xml/transform/sax/SAXResult.java \
  luni/src/main/java/javax/xml/transform/sax/SAXSource.java \
  luni/src/main/java/javax/xml/transform/sax/SAXTransformerFactory.java \
  luni/src/main/java/javax/xml/transform/sax/TemplatesHandler.java \
  luni/src/main/java/javax/xml/transform/sax/TransformerHandler.java \
  luni/src/main/java/javax/xml/transform/stream/FilePathToURI.java \
  luni/src/main/java/javax/xml/transform/stream/StreamResult.java \
  luni/src/main/java/javax/xml/transform/stream/StreamSource.java \
  luni/src/main/java/javax/xml/validation/Schema.java \
  luni/src/main/java/javax/xml/validation/SchemaFactory.java \
  luni/src/main/java/javax/xml/validation/SchemaFactoryFinder.java \
  luni/src/main/java/javax/xml/validation/SchemaFactoryLoader.java \
  luni/src/main/java/javax/xml/validation/TypeInfoProvider.java \
  luni/src/main/java/javax/xml/validation/Validator.java \
  luni/src/main/java/javax/xml/validation/ValidatorHandler.java \
  luni/src/main/java/javax/xml/xpath/XPath.java \
  luni/src/main/java/javax/xml/xpath/XPathConstants.java \
  luni/src/main/java/javax/xml/xpath/XPathException.java \
  luni/src/main/java/javax/xml/xpath/XPathExpression.java \
  luni/src/main/java/javax/xml/xpath/XPathExpressionException.java \
  luni/src/main/java/javax/xml/xpath/XPathFactory.java \
  luni/src/main/java/javax/xml/xpath/XPathFactoryConfigurationException.java \
  luni/src/main/java/javax/xml/xpath/XPathFactoryFinder.java \
  luni/src/main/java/javax/xml/xpath/XPathFunction.java \
  luni/src/main/java/javax/xml/xpath/XPathFunctionException.java \
  luni/src/main/java/javax/xml/xpath/XPathFunctionResolver.java \
  luni/src/main/java/javax/xml/xpath/XPathVariableResolver.java \
  json/src/main/java/org/json/JSON.java \
  json/src/main/java/org/json/JSONArray.java \
  json/src/main/java/org/json/JSONException.java \
  json/src/main/java/org/json/JSONObject.java \
  json/src/main/java/org/json/JSONStringer.java \
  json/src/main/java/org/json/JSONTokener.java \
  luni/src/main/java/org/w3c/dom/Attr.java \
  luni/src/main/java/org/w3c/dom/CDATASection.java \
  luni/src/main/java/org/w3c/dom/CharacterData.java \
  luni/src/main/java/org/w3c/dom/Comment.java \
  luni/src/main/java/org/w3c/dom/DOMConfiguration.java \
  luni/src/main/java/org/w3c/dom/DOMError.java \
  luni/src/main/java/org/w3c/dom/DOMErrorHandler.java \
  luni/src/main/java/org/w3c/dom/DOMException.java \
  luni/src/main/java/org/w3c/dom/DOMImplementation.java \
  luni/src/main/java/org/w3c/dom/DOMImplementationList.java \
  luni/src/main/java/org/w3c/dom/DOMImplementationSource.java \
  luni/src/main/java/org/w3c/dom/DOMLocator.java \
  luni/src/main/java/org/w3c/dom/DOMStringList.java \
  luni/src/main/java/org/w3c/dom/Document.java \
  luni/src/main/java/org/w3c/dom/DocumentFragment.java \
  luni/src/main/java/org/w3c/dom/DocumentType.java \
  luni/src/main/java/org/w3c/dom/Element.java \
  luni/src/main/java/org/w3c/dom/Entity.java \
  luni/src/main/java/org/w3c/dom/EntityReference.java \
  luni/src/main/java/org/w3c/dom/NameList.java \
  luni/src/main/java/org/w3c/dom/NamedNodeMap.java \
  luni/src/main/java/org/w3c/dom/Node.java \
  luni/src/main/java/org/w3c/dom/NodeList.java \
  luni/src/main/java/org/w3c/dom/Notation.java \
  luni/src/main/java/org/w3c/dom/ProcessingInstruction.java \
  luni/src/main/java/org/w3c/dom/Text.java \
  luni/src/main/java/org/w3c/dom/TypeInfo.java \
  luni/src/main/java/org/w3c/dom/UserDataHandler.java \
  luni/src/main/java/org/w3c/dom/ls/DOMImplementationLS.java \
  luni/src/main/java/org/w3c/dom/ls/LSException.java \
  luni/src/main/java/org/w3c/dom/ls/LSInput.java \
  luni/src/main/java/org/w3c/dom/ls/LSOutput.java \
  luni/src/main/java/org/w3c/dom/ls/LSParser.java \
  luni/src/main/java/org/w3c/dom/ls/LSParserFilter.java \
  luni/src/main/java/org/w3c/dom/ls/LSResourceResolver.java \
  luni/src/main/java/org/w3c/dom/ls/LSSerializer.java \
  luni/src/main/java/org/w3c/dom/ls/LSSerializerFilter.java \
  luni/src/main/java/org/w3c/dom/traversal/NodeFilter.java \
  luni/src/main/java/org/w3c/dom/traversal/NodeIterator.java \
  luni/src/main/java/org/xml/sax/AttributeList.java \
  luni/src/main/java/org/xml/sax/Attributes.java \
  luni/src/main/java/org/xml/sax/ContentHandler.java \
  luni/src/main/java/org/xml/sax/DTDHandler.java \
  luni/src/main/java/org/xml/sax/DocumentHandler.java \
  luni/src/main/java/org/xml/sax/EntityResolver.java \
  luni/src/main/java/org/xml/sax/ErrorHandler.java \
  luni/src/main/java/org/xml/sax/HandlerBase.java \
  luni/src/main/java/org/xml/sax/InputSource.java \
  luni/src/main/java/org/xml/sax/Locator.java \
  luni/src/main/java/org/xml/sax/Parser.java \
  luni/src/main/java/org/xml/sax/SAXException.java \
  luni/src/main/java/org/xml/sax/SAXNotRecognizedException.java \
  luni/src/main/java/org/xml/sax/SAXNotSupportedException.java \
  luni/src/main/java/org/xml/sax/SAXParseException.java \
  luni/src/main/java/org/xml/sax/XMLFilter.java \
  luni/src/main/java/org/xml/sax/XMLReader.java \
  luni/src/main/java/org/xml/sax/ext/Attributes2.java \
  luni/src/main/java/org/xml/sax/ext/Attributes2Impl.java \
  luni/src/main/java/org/xml/sax/ext/DeclHandler.java \
  luni/src/main/java/org/xml/sax/ext/DefaultHandler2.java \
  luni/src/main/java/org/xml/sax/ext/EntityResolver2.java \
  luni/src/main/java/org/xml/sax/ext/LexicalHandler.java \
  luni/src/main/java/org/xml/sax/ext/Locator2.java \
  luni/src/main/java/org/xml/sax/ext/Locator2Impl.java \
  luni/src/main/java/org/xml/sax/helpers/AttributeListImpl.java \
  luni/src/main/java/org/xml/sax/helpers/AttributesImpl.java \
  luni/src/main/java/org/xml/sax/helpers/DefaultHandler.java \
  luni/src/main/java/org/xml/sax/helpers/LocatorImpl.java \
  luni/src/main/java/org/xml/sax/helpers/NamespaceSupport.java \
  luni/src/main/java/org/xml/sax/helpers/NewInstance.java \
  luni/src/main/java/org/xml/sax/helpers/ParserAdapter.java \
  luni/src/main/java/org/xml/sax/helpers/ParserFactory.java \
  luni/src/main/java/org/xml/sax/helpers/XMLFilterImpl.java \
  luni/src/main/java/org/xml/sax/helpers/XMLReaderAdapter.java \
  luni/src/main/java/org/xml/sax/helpers/XMLReaderFactory.java \
  xml/src/main/java/org/xmlpull/v1/XmlPullParser.java \
  xml/src/main/java/org/xmlpull/v1/XmlPullParserException.java \
  xml/src/main/java/org/xmlpull/v1/XmlPullParserFactory.java \
  xml/src/main/java/org/xmlpull/v1/XmlSerializer.java \
  xml/src/main/java/org/xmlpull/v1/sax2/Driver.java \

non_openjdk_java_files := \
  dex/src/main/java/com/android/dex/Annotation.java \
  dex/src/main/java/com/android/dex/ClassData.java \
  dex/src/main/java/com/android/dex/ClassDef.java \
  dex/src/main/java/com/android/dex/Code.java \
  dex/src/main/java/com/android/dex/Dex.java \
  dex/src/main/java/com/android/dex/DexException.java \
  dex/src/main/java/com/android/dex/DexFormat.java \
  dex/src/main/java/com/android/dex/DexIndexOverflowException.java \
  dex/src/main/java/com/android/dex/EncodedValue.java \
  dex/src/main/java/com/android/dex/EncodedValueCodec.java \
  dex/src/main/java/com/android/dex/EncodedValueReader.java \
  dex/src/main/java/com/android/dex/FieldId.java \
  dex/src/main/java/com/android/dex/Leb128.java \
  dex/src/main/java/com/android/dex/MethodId.java \
  dex/src/main/java/com/android/dex/Mutf8.java \
  dex/src/main/java/com/android/dex/ProtoId.java \
  dex/src/main/java/com/android/dex/SizeOf.java \
  dex/src/main/java/com/android/dex/TableOfContents.java \
  dex/src/main/java/com/android/dex/TypeList.java \
  dex/src/main/java/com/android/dex/util/ByteArrayByteInput.java \
  dex/src/main/java/com/android/dex/util/ByteInput.java \
  dex/src/main/java/com/android/dex/util/ByteOutput.java \
  dex/src/main/java/com/android/dex/util/ExceptionWithContext.java \
  dex/src/main/java/com/android/dex/util/FileUtils.java \
  dex/src/main/java/com/android/dex/util/Unsigned.java \
  dalvik/src/main/java/dalvik/system/profiler/AsciiHprofWriter.java \
  dalvik/src/main/java/dalvik/system/profiler/BinaryHprof.java \
  dalvik/src/main/java/dalvik/system/profiler/BinaryHprofReader.java \
  dalvik/src/main/java/dalvik/system/profiler/BinaryHprofWriter.java \
  dalvik/src/main/java/dalvik/system/profiler/DalvikThreadSampler.java \
  dalvik/src/main/java/dalvik/system/profiler/HprofBinaryToAscii.java \
  dalvik/src/main/java/dalvik/system/profiler/HprofData.java \
  dalvik/src/main/java/dalvik/system/profiler/MalformedHprofException.java \
  dalvik/src/main/java/dalvik/system/profiler/PortableThreadSampler.java \
  dalvik/src/main/java/dalvik/system/profiler/SamplingProfiler.java \
  dalvik/src/main/java/dalvik/system/profiler/ThreadSampler.java \
  luni/src/main/java/android/system/UnixSocketAddress.java \
  luni/src/main/java/java/net/AddressCache.java \
  luni/src/main/java/libcore/icu/CollationKeyICU.java \
  luni/src/main/java/libcore/icu/DateIntervalFormat.java \
  luni/src/main/java/libcore/icu/DateTimeFormat.java \
  luni/src/main/java/libcore/icu/DateUtilsBridge.java \
  luni/src/main/java/libcore/icu/ICU.java \
  luni/src/main/java/libcore/icu/LocaleData.java \
  luni/src/main/java/libcore/icu/NativeConverter.java \
  luni/src/main/java/libcore/icu/RelativeDateTimeFormatter.java \
  luni/src/main/java/libcore/icu/TimeZoneNames.java \
  luni/src/main/java/libcore/internal/StringPool.java \
  luni/src/main/java/libcore/io/AsynchronousCloseMonitor.java \
  luni/src/main/java/libcore/io/ClassPathURLStreamHandler.java \
  luni/src/main/java/libcore/io/Base64.java \
  luni/src/main/java/libcore/io/BlockGuardOs.java \
  luni/src/main/java/libcore/io/BufferIterator.java \
  luni/src/main/java/libcore/io/DropBox.java \
  luni/src/main/java/libcore/io/EventLogger.java \
  luni/src/main/java/libcore/io/ForwardingOs.java \
  luni/src/main/java/libcore/io/IoBridge.java \
  luni/src/main/java/libcore/io/IoUtils.java \
  luni/src/main/java/libcore/io/Libcore.java \
  luni/src/main/java/libcore/io/Memory.java \
  luni/src/main/java/libcore/io/MemoryMappedFile.java \
  luni/src/main/java/libcore/io/NioBufferIterator.java \
  luni/src/main/java/libcore/io/Os.java \
  luni/src/main/java/libcore/io/Posix.java \
  luni/src/main/java/libcore/io/SizeOf.java \
  luni/src/main/java/libcore/io/Streams.java \
  luni/src/main/java/libcore/math/MathUtils.java \
  luni/src/main/java/libcore/net/MimeUtils.java \
  luni/src/main/java/libcore/net/NetworkSecurityPolicy.java \
  luni/src/main/java/libcore/net/UriCodec.java \
  luni/src/main/java/libcore/net/event/NetworkEventDispatcher.java \
  luni/src/main/java/libcore/net/event/NetworkEventListener.java \
  luni/src/main/java/libcore/net/http/HttpDate.java \
  luni/src/main/java/libcore/net/http/ResponseUtils.java \
  luni/src/main/java/libcore/reflect/AnnotatedElements.java \
  luni/src/main/java/libcore/reflect/AnnotationFactory.java \
  luni/src/main/java/libcore/reflect/AnnotationMember.java \
  luni/src/main/java/libcore/reflect/GenericArrayTypeImpl.java \
  luni/src/main/java/libcore/reflect/GenericSignatureParser.java \
  luni/src/main/java/libcore/reflect/InternalNames.java \
  luni/src/main/java/libcore/reflect/ListOfTypes.java \
  luni/src/main/java/libcore/reflect/ListOfVariables.java \
  luni/src/main/java/libcore/reflect/ParameterizedTypeImpl.java \
  luni/src/main/java/libcore/reflect/TypeVariableImpl.java \
  luni/src/main/java/libcore/reflect/Types.java \
  luni/src/main/java/libcore/reflect/WildcardTypeImpl.java \
  luni/src/main/java/libcore/util/CharsetUtils.java \
  luni/src/main/java/libcore/util/EmptyArray.java \
  luni/src/main/java/libcore/util/BasicLruCache.java \
  luni/src/main/java/libcore/util/CollectionUtils.java \
  luni/src/main/java/libcore/util/EmptyArray.java \
  luni/src/main/java/libcore/util/NativeAllocationRegistry.java \
  luni/src/main/java/libcore/util/Objects.java \
  luni/src/main/java/libcore/util/RecoverySystem.java \
  luni/src/main/java/libcore/util/SneakyThrow.java \
  luni/src/main/java/libcore/util/ZoneInfo.java \
  luni/src/main/java/libcore/util/ZoneInfoDB.java \
  luni/src/main/java/libcore/util/HexEncoding.java \
  dalvik/src/main/java/org/apache/harmony/dalvik/NativeTestTarget.java \
  dalvik/src/main/java/org/apache/harmony/dalvik/ddmc/Chunk.java \
  dalvik/src/main/java/org/apache/harmony/dalvik/ddmc/ChunkHandler.java \
  dalvik/src/main/java/org/apache/harmony/dalvik/ddmc/DdmServer.java \
  dalvik/src/main/java/org/apache/harmony/dalvik/ddmc/DdmVmInternal.java \
  luni/src/main/java/org/apache/harmony/luni/internal/util/TimezoneGetter.java \
  luni/src/main/java/org/apache/harmony/xml/ExpatAttributes.java \
  luni/src/main/java/org/apache/harmony/xml/ExpatException.java \
  luni/src/main/java/org/apache/harmony/xml/ExpatParser.java \
  luni/src/main/java/org/apache/harmony/xml/ExpatReader.java \
  luni/src/main/java/org/apache/harmony/xml/dom/AttrImpl.java \
  luni/src/main/java/org/apache/harmony/xml/dom/CDATASectionImpl.java \
  luni/src/main/java/org/apache/harmony/xml/dom/CharacterDataImpl.java \
  luni/src/main/java/org/apache/harmony/xml/dom/CommentImpl.java \
  luni/src/main/java/org/apache/harmony/xml/dom/DOMConfigurationImpl.java \
  luni/src/main/java/org/apache/harmony/xml/dom/DOMErrorImpl.java \
  luni/src/main/java/org/apache/harmony/xml/dom/DOMImplementationImpl.java \
  luni/src/main/java/org/apache/harmony/xml/dom/DocumentFragmentImpl.java \
  luni/src/main/java/org/apache/harmony/xml/dom/DocumentImpl.java \
  luni/src/main/java/org/apache/harmony/xml/dom/DocumentTypeImpl.java \
  luni/src/main/java/org/apache/harmony/xml/dom/ElementImpl.java \
  luni/src/main/java/org/apache/harmony/xml/dom/EntityImpl.java \
  luni/src/main/java/org/apache/harmony/xml/dom/EntityReferenceImpl.java \
  luni/src/main/java/org/apache/harmony/xml/dom/InnerNodeImpl.java \
  luni/src/main/java/org/apache/harmony/xml/dom/LeafNodeImpl.java \
  luni/src/main/java/org/apache/harmony/xml/dom/NodeImpl.java \
  luni/src/main/java/org/apache/harmony/xml/dom/NodeListImpl.java \
  luni/src/main/java/org/apache/harmony/xml/dom/NotationImpl.java \
  luni/src/main/java/org/apache/harmony/xml/dom/ProcessingInstructionImpl.java \
  luni/src/main/java/org/apache/harmony/xml/dom/TextImpl.java \
  luni/src/main/java/org/apache/harmony/xml/parsers/DocumentBuilderFactoryImpl.java \
  luni/src/main/java/org/apache/harmony/xml/parsers/DocumentBuilderImpl.java \
  luni/src/main/java/org/apache/harmony/xml/parsers/SAXParserFactoryImpl.java \
  luni/src/main/java/org/apache/harmony/xml/parsers/SAXParserImpl.java \
  libart/src/main/java/java/lang/CaseMapper.java \
  libart/src/main/java/java/lang/StringFactory.java \
  xml/src/main/java/org/kxml2/io/KXmlParser.java \
  xml/src/main/java/org/kxml2/io/KXmlSerializer.java \
  $(non_openjdk_javadoc_files)
