/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_io_FileOutputStream */

#ifndef _Included_java_io_FileOutputStream
#define _Included_java_io_FileOutputStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_io_FileOutputStream
 * Method:    open
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_java_io_FileOutputStream_open
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     java_io_FileOutputStream
 * Method:    write
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_java_io_FileOutputStream_write
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     java_io_FileOutputStream
 * Method:    writeBytes
 * Signature: ([BIIZ)V
 */
JNIEXPORT void JNICALL Java_java_io_FileOutputStream_writeBytes
  (JNIEnv *, jobject, jbyteArray, jint, jint, jboolean);

/*
 * Class:     java_io_FileOutputStream
 * Method:    close0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_io_FileOutputStream_close0
  (JNIEnv *, jobject);

/*
 * Class:     java_io_FileOutputStream
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_io_FileOutputStream_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
