/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_Long */

#ifndef _Included_java_lang_Long
#define _Included_java_lang_Long
#ifdef __cplusplus
extern "C" {
#endif
#undef java_lang_Long_serialVersionUID
#define java_lang_Long_serialVersionUID -8742448824652078965LL
#undef java_lang_Long_MIN_VALUE
#define java_lang_Long_MIN_VALUE -9223372036854775808LL
#undef java_lang_Long_MAX_VALUE
#define java_lang_Long_MAX_VALUE 9223372036854775807LL
#undef java_lang_Long_SIZE
#define java_lang_Long_SIZE 64L
#undef java_lang_Long_serialVersionUID
#define java_lang_Long_serialVersionUID 4290774380558885855LL
#ifdef __cplusplus
}
#endif
#endif
