/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_net_Inet6Address */

#ifndef _Included_java_net_Inet6Address
#define _Included_java_net_Inet6Address
#ifdef __cplusplus
extern "C" {
#endif
#undef java_net_Inet6Address_IPv4
#define java_net_Inet6Address_IPv4 1L
#undef java_net_Inet6Address_IPv6
#define java_net_Inet6Address_IPv6 2L
#undef java_net_Inet6Address_serialVersionUID
#define java_net_Inet6Address_serialVersionUID 3286316764910316507LL
#undef java_net_Inet6Address_maxCacheTime
#define java_net_Inet6Address_maxCacheTime 5000LL
#undef java_net_Inet6Address_INADDRSZ
#define java_net_Inet6Address_INADDRSZ 16L
#undef java_net_Inet6Address_serialVersionUID
#define java_net_Inet6Address_serialVersionUID 6880410070516793377LL
#undef java_net_Inet6Address_INT16SZ
#define java_net_Inet6Address_INT16SZ 2L
/*
 * Class:     java_net_Inet6Address
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_net_Inet6Address_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
