/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_net_InetAddress */

#ifndef _Included_java_net_InetAddress
#define _Included_java_net_InetAddress
#ifdef __cplusplus
extern "C" {
#endif
#undef java_net_InetAddress_IPv4
#define java_net_InetAddress_IPv4 1L
#undef java_net_InetAddress_IPv6
#define java_net_InetAddress_IPv6 2L
#undef java_net_InetAddress_serialVersionUID
#define java_net_InetAddress_serialVersionUID 3286316764910316507LL
#undef java_net_InetAddress_maxCacheTime
#define java_net_InetAddress_maxCacheTime 5000LL
/*
 * Class:     java_net_InetAddress
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_net_InetAddress_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
