/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_io_FileSystem */

#ifndef _Included_java_io_FileSystem
#define _Included_java_io_FileSystem
#ifdef __cplusplus
extern "C" {
#endif
#undef java_io_FileSystem_BA_EXISTS
#define java_io_FileSystem_BA_EXISTS 1L
#undef java_io_FileSystem_BA_REGULAR
#define java_io_FileSystem_BA_REGULAR 2L
#undef java_io_FileSystem_BA_DIRECTORY
#define java_io_FileSystem_BA_DIRECTORY 4L
#undef java_io_FileSystem_BA_HIDDEN
#define java_io_FileSystem_BA_HIDDEN 8L
#undef java_io_FileSystem_ACCESS_READ
#define java_io_FileSystem_ACCESS_READ 4L
#undef java_io_FileSystem_ACCESS_WRITE
#define java_io_FileSystem_ACCESS_WRITE 2L
#undef java_io_FileSystem_ACCESS_EXECUTE
#define java_io_FileSystem_ACCESS_EXECUTE 1L
#undef java_io_FileSystem_SPACE_TOTAL
#define java_io_FileSystem_SPACE_TOTAL 0L
#undef java_io_FileSystem_SPACE_FREE
#define java_io_FileSystem_SPACE_FREE 1L
#undef java_io_FileSystem_SPACE_USABLE
#define java_io_FileSystem_SPACE_USABLE 2L
/*
 * Class:     java_io_FileSystem
 * Method:    getFileSystem
 * Signature: ()Ljava/io/FileSystem;
 */
JNIEXPORT jobject JNICALL Java_java_io_FileSystem_getFileSystem
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
