/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_util_zip_ZipFile */

#ifndef _Included_java_util_zip_ZipFile
#define _Included_java_util_zip_ZipFile
#ifdef __cplusplus
extern "C" {
#endif
#undef java_util_zip_ZipFile_STORED
#define java_util_zip_ZipFile_STORED 0L
#undef java_util_zip_ZipFile_DEFLATED
#define java_util_zip_ZipFile_DEFLATED 8L
#undef java_util_zip_ZipFile_OPEN_READ
#define java_util_zip_ZipFile_OPEN_READ 1L
#undef java_util_zip_ZipFile_OPEN_DELETE
#define java_util_zip_ZipFile_OPEN_DELETE 4L
#undef java_util_zip_ZipFile_JZENTRY_NAME
#define java_util_zip_ZipFile_JZENTRY_NAME 0L
#undef java_util_zip_ZipFile_JZENTRY_EXTRA
#define java_util_zip_ZipFile_JZENTRY_EXTRA 1L
#undef java_util_zip_ZipFile_JZENTRY_COMMENT
#define java_util_zip_ZipFile_JZENTRY_COMMENT 2L
/*
 * Class:     java_util_zip_ZipFile
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_util_zip_ZipFile_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     java_util_zip_ZipFile
 * Method:    getEntry
 * Signature: (J[BZ)J
 */
JNIEXPORT jlong JNICALL Java_java_util_zip_ZipFile_getEntry
  (JNIEnv *, jclass, jlong, jbyteArray, jboolean);

/*
 * Class:     java_util_zip_ZipFile
 * Method:    freeEntry
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_java_util_zip_ZipFile_freeEntry
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     java_util_zip_ZipFile
 * Method:    getNextEntry
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_java_util_zip_ZipFile_getNextEntry
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     java_util_zip_ZipFile
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_java_util_zip_ZipFile_close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     java_util_zip_ZipFile
 * Method:    open
 * Signature: (Ljava/lang/String;IJZ)J
 */
JNIEXPORT jlong JNICALL Java_java_util_zip_ZipFile_open
  (JNIEnv *, jclass, jstring, jint, jlong, jboolean);

/*
 * Class:     java_util_zip_ZipFile
 * Method:    getTotal
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_java_util_zip_ZipFile_getTotal
  (JNIEnv *, jclass, jlong);

/*
 * Class:     java_util_zip_ZipFile
 * Method:    startsWithLOC
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_java_util_zip_ZipFile_startsWithLOC
  (JNIEnv *, jclass, jlong);

/*
 * Class:     java_util_zip_ZipFile
 * Method:    read
 * Signature: (JJJ[BII)I
 */
JNIEXPORT jint JNICALL Java_java_util_zip_ZipFile_read
  (JNIEnv *, jclass, jlong, jlong, jlong, jbyteArray, jint, jint);

/*
 * Class:     java_util_zip_ZipFile
 * Method:    getEntryTime
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_java_util_zip_ZipFile_getEntryTime
  (JNIEnv *, jclass, jlong);

/*
 * Class:     java_util_zip_ZipFile
 * Method:    getEntryCrc
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_java_util_zip_ZipFile_getEntryCrc
  (JNIEnv *, jclass, jlong);

/*
 * Class:     java_util_zip_ZipFile
 * Method:    getEntryCSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_java_util_zip_ZipFile_getEntryCSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     java_util_zip_ZipFile
 * Method:    getEntrySize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_java_util_zip_ZipFile_getEntrySize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     java_util_zip_ZipFile
 * Method:    getEntryMethod
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_java_util_zip_ZipFile_getEntryMethod
  (JNIEnv *, jclass, jlong);

/*
 * Class:     java_util_zip_ZipFile
 * Method:    getEntryFlag
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_java_util_zip_ZipFile_getEntryFlag
  (JNIEnv *, jclass, jlong);

/*
 * Class:     java_util_zip_ZipFile
 * Method:    getCommentBytes
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_java_util_zip_ZipFile_getCommentBytes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     java_util_zip_ZipFile
 * Method:    getEntryBytes
 * Signature: (JI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_java_util_zip_ZipFile_getEntryBytes
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     java_util_zip_ZipFile
 * Method:    getZipMessage
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_java_util_zip_ZipFile_getZipMessage
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
