/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_Throwable */

#ifndef _Included_java_lang_Throwable
#define _Included_java_lang_Throwable
#ifdef __cplusplus
extern "C" {
#endif
#undef java_lang_Throwable_serialVersionUID
#define java_lang_Throwable_serialVersionUID -3042686055658047285LL
/*
 * Class:     java_lang_Throwable
 * Method:    fillInStackTrace
 * Signature: (I)Ljava/lang/Throwable;
 */
JNIEXPORT jthrowable JNICALL Java_java_lang_Throwable_fillInStackTrace
  (JNIEnv *, jobject, jint);

/*
 * Class:     java_lang_Throwable
 * Method:    getStackTraceDepth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_java_lang_Throwable_getStackTraceDepth
  (JNIEnv *, jobject);

/*
 * Class:     java_lang_Throwable
 * Method:    getStackTraceElement
 * Signature: (I)Ljava/lang/StackTraceElement;
 */
JNIEXPORT jobject JNICALL Java_java_lang_Throwable_getStackTraceElement
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
