/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_net_Inet4Address */

#ifndef _Included_java_net_Inet4Address
#define _Included_java_net_Inet4Address
#ifdef __cplusplus
extern "C" {
#endif
#undef java_net_Inet4Address_IPv4
#define java_net_Inet4Address_IPv4 1L
#undef java_net_Inet4Address_IPv6
#define java_net_Inet4Address_IPv6 2L
#undef java_net_Inet4Address_serialVersionUID
#define java_net_Inet4Address_serialVersionUID 3286316764910316507LL
#undef java_net_Inet4Address_maxCacheTime
#define java_net_Inet4Address_maxCacheTime 5000LL
#undef java_net_Inet4Address_INADDRSZ
#define java_net_Inet4Address_INADDRSZ 4L
#undef java_net_Inet4Address_serialVersionUID
#define java_net_Inet4Address_serialVersionUID 3286316764910316507LL
#undef java_net_Inet4Address_loopback
#define java_net_Inet4Address_loopback 2130706433L
/*
 * Class:     java_net_Inet4Address
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_net_Inet4Address_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
