/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_net_InetAddressImplFactory */

#ifndef _Included_java_net_InetAddressImplFactory
#define _Included_java_net_InetAddressImplFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_net_InetAddressImplFactory
 * Method:    isIPv6Supported
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_java_net_InetAddressImplFactory_isIPv6Supported
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
