/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_net_SocketOutputStream */

#ifndef _Included_java_net_SocketOutputStream
#define _Included_java_net_SocketOutputStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_net_SocketOutputStream
 * Method:    socketWrite0
 * Signature: (Ljava/io/FileDescriptor;[BII)V
 */
JNIEXPORT void JNICALL Java_java_net_SocketOutputStream_socketWrite0
  (JNIEnv *, jobject, jobject, jbyteArray, jint, jint);

/*
 * Class:     java_net_SocketOutputStream
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_net_SocketOutputStream_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
