/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_StrictMath */

#ifndef _Included_java_lang_StrictMath
#define _Included_java_lang_StrictMath
#ifdef __cplusplus
extern "C" {
#endif
#undef java_lang_StrictMath_E
#define java_lang_StrictMath_E 2.718281828459045
#undef java_lang_StrictMath_PI
#define java_lang_StrictMath_PI 3.141592653589793
/*
 * Class:     java_lang_StrictMath
 * Method:    sin
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_StrictMath_sin
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     java_lang_StrictMath
 * Method:    cos
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_StrictMath_cos
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     java_lang_StrictMath
 * Method:    tan
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_StrictMath_tan
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     java_lang_StrictMath
 * Method:    asin
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_StrictMath_asin
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     java_lang_StrictMath
 * Method:    acos
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_StrictMath_acos
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     java_lang_StrictMath
 * Method:    atan
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_StrictMath_atan
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     java_lang_StrictMath
 * Method:    exp
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_StrictMath_exp
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     java_lang_StrictMath
 * Method:    log
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_StrictMath_log
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     java_lang_StrictMath
 * Method:    log10
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_StrictMath_log10
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     java_lang_StrictMath
 * Method:    sqrt
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_StrictMath_sqrt
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     java_lang_StrictMath
 * Method:    cbrt
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_StrictMath_cbrt
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     java_lang_StrictMath
 * Method:    IEEEremainder
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_StrictMath_IEEEremainder
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     java_lang_StrictMath
 * Method:    atan2
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_StrictMath_atan2
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     java_lang_StrictMath
 * Method:    pow
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_StrictMath_pow
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     java_lang_StrictMath
 * Method:    sinh
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_StrictMath_sinh
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     java_lang_StrictMath
 * Method:    cosh
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_StrictMath_cosh
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     java_lang_StrictMath
 * Method:    tanh
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_StrictMath_tanh
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     java_lang_StrictMath
 * Method:    hypot
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_StrictMath_hypot
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     java_lang_StrictMath
 * Method:    expm1
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_StrictMath_expm1
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     java_lang_StrictMath
 * Method:    log1p
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_StrictMath_log1p
  (JNIEnv *, jclass, jdouble);

#ifdef __cplusplus
}
#endif
#endif
