/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_net_PlainDatagramSocketImpl */

#ifndef _Included_java_net_PlainDatagramSocketImpl
#define _Included_java_net_PlainDatagramSocketImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_net_PlainDatagramSocketImpl
 * Method:    bind0
 * Signature: (ILjava/net/InetAddress;)V
 */
JNIEXPORT void JNICALL Java_java_net_PlainDatagramSocketImpl_bind0
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     java_net_PlainDatagramSocketImpl
 * Method:    send
 * Signature: (Ljava/net/DatagramPacket;)V
 */
JNIEXPORT void JNICALL Java_java_net_PlainDatagramSocketImpl_send
  (JNIEnv *, jobject, jobject);

/*
 * Class:     java_net_PlainDatagramSocketImpl
 * Method:    peek
 * Signature: (Ljava/net/InetAddress;)I
 */
JNIEXPORT jint JNICALL Java_java_net_PlainDatagramSocketImpl_peek
  (JNIEnv *, jobject, jobject);

/*
 * Class:     java_net_PlainDatagramSocketImpl
 * Method:    peekData
 * Signature: (Ljava/net/DatagramPacket;)I
 */
JNIEXPORT jint JNICALL Java_java_net_PlainDatagramSocketImpl_peekData
  (JNIEnv *, jobject, jobject);

/*
 * Class:     java_net_PlainDatagramSocketImpl
 * Method:    receive0
 * Signature: (Ljava/net/DatagramPacket;)V
 */
JNIEXPORT void JNICALL Java_java_net_PlainDatagramSocketImpl_receive0
  (JNIEnv *, jobject, jobject);

/*
 * Class:     java_net_PlainDatagramSocketImpl
 * Method:    setTimeToLive
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_java_net_PlainDatagramSocketImpl_setTimeToLive
  (JNIEnv *, jobject, jint);

/*
 * Class:     java_net_PlainDatagramSocketImpl
 * Method:    getTimeToLive
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_java_net_PlainDatagramSocketImpl_getTimeToLive
  (JNIEnv *, jobject);

/*
 * Class:     java_net_PlainDatagramSocketImpl
 * Method:    setTTL
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_java_net_PlainDatagramSocketImpl_setTTL
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     java_net_PlainDatagramSocketImpl
 * Method:    getTTL
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_java_net_PlainDatagramSocketImpl_getTTL
  (JNIEnv *, jobject);

/*
 * Class:     java_net_PlainDatagramSocketImpl
 * Method:    join
 * Signature: (Ljava/net/InetAddress;Ljava/net/NetworkInterface;)V
 */
JNIEXPORT void JNICALL Java_java_net_PlainDatagramSocketImpl_join
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     java_net_PlainDatagramSocketImpl
 * Method:    leave
 * Signature: (Ljava/net/InetAddress;Ljava/net/NetworkInterface;)V
 */
JNIEXPORT void JNICALL Java_java_net_PlainDatagramSocketImpl_leave
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     java_net_PlainDatagramSocketImpl
 * Method:    datagramSocketCreate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_net_PlainDatagramSocketImpl_datagramSocketCreate
  (JNIEnv *, jobject);

/*
 * Class:     java_net_PlainDatagramSocketImpl
 * Method:    datagramSocketClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_net_PlainDatagramSocketImpl_datagramSocketClose
  (JNIEnv *, jobject);

/*
 * Class:     java_net_PlainDatagramSocketImpl
 * Method:    socketSetOption
 * Signature: (ILjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_java_net_PlainDatagramSocketImpl_socketSetOption
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     java_net_PlainDatagramSocketImpl
 * Method:    socketGetOption
 * Signature: (I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_java_net_PlainDatagramSocketImpl_socketGetOption
  (JNIEnv *, jobject, jint);

/*
 * Class:     java_net_PlainDatagramSocketImpl
 * Method:    connect0
 * Signature: (Ljava/net/InetAddress;I)V
 */
JNIEXPORT void JNICALL Java_java_net_PlainDatagramSocketImpl_connect0
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     java_net_PlainDatagramSocketImpl
 * Method:    disconnect0
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_java_net_PlainDatagramSocketImpl_disconnect0
  (JNIEnv *, jobject, jint);

/*
 * Class:     java_net_PlainDatagramSocketImpl
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_net_PlainDatagramSocketImpl_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
