/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_io_Console */

#ifndef _Included_java_io_Console
#define _Included_java_io_Console
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_io_Console
 * Method:    encoding
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_java_io_Console_encoding
  (JNIEnv *, jclass);

/*
 * Class:     java_io_Console
 * Method:    echo
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_Console_echo
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     java_io_Console
 * Method:    istty
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_Console_istty
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
