/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_Integer */

#ifndef _Included_java_lang_Integer
#define _Included_java_lang_Integer
#ifdef __cplusplus
extern "C" {
#endif
#undef java_lang_Integer_serialVersionUID
#define java_lang_Integer_serialVersionUID -8742448824652078965LL
#undef java_lang_Integer_MIN_VALUE
#define java_lang_Integer_MIN_VALUE -2147483648L
#undef java_lang_Integer_MAX_VALUE
#define java_lang_Integer_MAX_VALUE 2147483647L
#undef java_lang_Integer_SIZE
#define java_lang_Integer_SIZE 32L
#undef java_lang_Integer_serialVersionUID
#define java_lang_Integer_serialVersionUID 1360826667806852920LL
#ifdef __cplusplus
}
#endif
#endif
