/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_io_ObjectOutputStream */

#ifndef _Included_java_io_ObjectOutputStream
#define _Included_java_io_ObjectOutputStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_io_ObjectOutputStream
 * Method:    floatsToBytes
 * Signature: ([FI[BII)V
 */
JNIEXPORT void JNICALL Java_java_io_ObjectOutputStream_floatsToBytes
  (JNIEnv *, jclass, jfloatArray, jint, jbyteArray, jint, jint);

/*
 * Class:     java_io_ObjectOutputStream
 * Method:    doublesToBytes
 * Signature: ([DI[BII)V
 */
JNIEXPORT void JNICALL Java_java_io_ObjectOutputStream_doublesToBytes
  (JNIEnv *, jclass, jdoubleArray, jint, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
