/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_nio_MappedByteBuffer */

#ifndef _Included_java_nio_MappedByteBuffer
#define _Included_java_nio_MappedByteBuffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_nio_MappedByteBuffer
 * Method:    isLoaded0
 * Signature: (JJI)Z
 */
JNIEXPORT jboolean JNICALL Java_java_nio_MappedByteBuffer_isLoaded0
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     java_nio_MappedByteBuffer
 * Method:    load0
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_java_nio_MappedByteBuffer_load0
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     java_nio_MappedByteBuffer
 * Method:    force0
 * Signature: (Ljava/io/FileDescriptor;JJ)V
 */
JNIEXPORT void JNICALL Java_java_nio_MappedByteBuffer_force0
  (JNIEnv *, jobject, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
