/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_io_ObjectStreamClass */

#ifndef _Included_java_io_ObjectStreamClass
#define _Included_java_io_ObjectStreamClass
#ifdef __cplusplus
extern "C" {
#endif
#undef java_io_ObjectStreamClass_serialVersionUID
#define java_io_ObjectStreamClass_serialVersionUID -6120832682080437368LL
/*
 * Class:     java_io_ObjectStreamClass
 * Method:    initNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_io_ObjectStreamClass_initNative
  (JNIEnv *, jclass);

/*
 * Class:     java_io_ObjectStreamClass
 * Method:    hasStaticInitializer
 * Signature: (Ljava/lang/Class;)Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_ObjectStreamClass_hasStaticInitializer
  (JNIEnv *, jclass, jclass);

#ifdef __cplusplus
}
#endif
#endif
