/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_net_DatagramPacket */

#ifndef _Included_java_net_DatagramPacket
#define _Included_java_net_DatagramPacket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_net_DatagramPacket
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_net_DatagramPacket_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
