/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_nio_ch_IOStatus */

#ifndef _Included_sun_nio_ch_IOStatus
#define _Included_sun_nio_ch_IOStatus
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_nio_ch_IOStatus_EOF
#define sun_nio_ch_IOStatus_EOF -1L
#undef sun_nio_ch_IOStatus_UNAVAILABLE
#define sun_nio_ch_IOStatus_UNAVAILABLE -2L
#undef sun_nio_ch_IOStatus_INTERRUPTED
#define sun_nio_ch_IOStatus_INTERRUPTED -3L
#undef sun_nio_ch_IOStatus_UNSUPPORTED
#define sun_nio_ch_IOStatus_UNSUPPORTED -4L
#undef sun_nio_ch_IOStatus_THROWN
#define sun_nio_ch_IOStatus_THROWN -5L
#undef sun_nio_ch_IOStatus_UNSUPPORTED_CASE
#define sun_nio_ch_IOStatus_UNSUPPORTED_CASE -6L
#ifdef __cplusplus
}
#endif
#endif
