/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_misc_Signal */

#ifndef _Included_sun_misc_Signal
#define _Included_sun_misc_Signal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_misc_Signal
 * Method:    findSignal
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_sun_misc_Signal_findSignal
  (JNIEnv *, jclass, jstring);

/*
 * Class:     sun_misc_Signal
 * Method:    handle0
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_sun_misc_Signal_handle0
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     sun_misc_Signal
 * Method:    raise0
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_sun_misc_Signal_raise0
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
