/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_nio_ch_EPollArrayWrapper */

#ifndef _Included_sun_nio_ch_EPollArrayWrapper
#define _Included_sun_nio_ch_EPollArrayWrapper
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_nio_ch_EPollArrayWrapper_EPOLLIN
#define sun_nio_ch_EPollArrayWrapper_EPOLLIN 1L
#undef sun_nio_ch_EPollArrayWrapper_EPOLL_CTL_ADD
#define sun_nio_ch_EPollArrayWrapper_EPOLL_CTL_ADD 1L
#undef sun_nio_ch_EPollArrayWrapper_EPOLL_CTL_DEL
#define sun_nio_ch_EPollArrayWrapper_EPOLL_CTL_DEL 2L
#undef sun_nio_ch_EPollArrayWrapper_EPOLL_CTL_MOD
#define sun_nio_ch_EPollArrayWrapper_EPOLL_CTL_MOD 3L
#undef sun_nio_ch_EPollArrayWrapper_EVENT_OFFSET
#define sun_nio_ch_EPollArrayWrapper_EVENT_OFFSET 0L
#undef sun_nio_ch_EPollArrayWrapper_KILLED
#define sun_nio_ch_EPollArrayWrapper_KILLED -1L
#undef sun_nio_ch_EPollArrayWrapper_INITIAL_PENDING_UPDATE_SIZE
#define sun_nio_ch_EPollArrayWrapper_INITIAL_PENDING_UPDATE_SIZE 64L
/*
 * Class:     sun_nio_ch_EPollArrayWrapper
 * Method:    epollCreate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_EPollArrayWrapper_epollCreate
  (JNIEnv *, jobject);

/*
 * Class:     sun_nio_ch_EPollArrayWrapper
 * Method:    epollCtl
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_sun_nio_ch_EPollArrayWrapper_epollCtl
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     sun_nio_ch_EPollArrayWrapper
 * Method:    epollWait
 * Signature: (JIJI)I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_EPollArrayWrapper_epollWait
  (JNIEnv *, jobject, jlong, jint, jlong, jint);

/*
 * Class:     sun_nio_ch_EPollArrayWrapper
 * Method:    sizeofEPollEvent
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_EPollArrayWrapper_sizeofEPollEvent
  (JNIEnv *, jclass);

/*
 * Class:     sun_nio_ch_EPollArrayWrapper
 * Method:    offsetofData
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_EPollArrayWrapper_offsetofData
  (JNIEnv *, jclass);

/*
 * Class:     sun_nio_ch_EPollArrayWrapper
 * Method:    interrupt
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_sun_nio_ch_EPollArrayWrapper_interrupt
  (JNIEnv *, jclass, jint);

/*
 * Class:     sun_nio_ch_EPollArrayWrapper
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_nio_ch_EPollArrayWrapper_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
