/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_nio_ch_FileKey */

#ifndef _Included_sun_nio_ch_FileKey
#define _Included_sun_nio_ch_FileKey
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_nio_ch_FileKey
 * Method:    init
 * Signature: (Ljava/io/FileDescriptor;)V
 */
JNIEXPORT void JNICALL Java_sun_nio_ch_FileKey_init
  (JNIEnv *, jobject, jobject);

/*
 * Class:     sun_nio_ch_FileKey
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_nio_ch_FileKey_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
