/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_misc_NativeSignalHandler */

#ifndef _Included_sun_misc_NativeSignalHandler
#define _Included_sun_misc_NativeSignalHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_misc_NativeSignalHandler
 * Method:    handle0
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_sun_misc_NativeSignalHandler_handle0
  (JNIEnv *, jclass, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
