/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_nio_ch_NativeThread */

#ifndef _Included_sun_nio_ch_NativeThread
#define _Included_sun_nio_ch_NativeThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_nio_ch_NativeThread
 * Method:    current
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_sun_nio_ch_NativeThread_current
  (JNIEnv *, jclass);

/*
 * Class:     sun_nio_ch_NativeThread
 * Method:    signal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sun_nio_ch_NativeThread_signal
  (JNIEnv *, jclass, jlong);

/*
 * Class:     sun_nio_ch_NativeThread
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_nio_ch_NativeThread_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
