/*
 * Copyright (C) 2011 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package libcore.io;

public class OsConstants {
    private OsConstants() { }

    // Generated by gen-os-constants.
    public static final int FD_CLOEXEC = get_FD_CLOEXEC();
    private static native int get_FD_CLOEXEC();
    public static final int F_DUPFD = get_F_DUPFD();
    private static native int get_F_DUPFD();
    public static final int F_GETFD = get_F_GETFD();
    private static native int get_F_GETFD();
    public static final int F_GETFL = get_F_GETFL();
    private static native int get_F_GETFL();
    public static final int F_GETLK = get_F_GETLK();
    private static native int get_F_GETLK();
    public static final int F_GETOWN = get_F_GETOWN();
    private static native int get_F_GETOWN();
    public static final int F_OK = get_F_OK();
    private static native int get_F_OK();
    public static final int F_RDLCK = get_F_RDLCK();
    private static native int get_F_RDLCK();
    public static final int F_SETFD = get_F_SETFD();
    private static native int get_F_SETFD();
    public static final int F_SETFL = get_F_SETFL();
    private static native int get_F_SETFL();
    public static final int F_SETLK = get_F_SETLK();
    private static native int get_F_SETLK();
    public static final int F_SETLKW = get_F_SETLKW();
    private static native int get_F_SETLKW();
    public static final int F_SETOWN = get_F_SETOWN();
    private static native int get_F_SETOWN();
    public static final int F_UNLCK = get_F_UNLCK();
    private static native int get_F_UNLCK();
    public static final int F_WRLCK = get_F_WRLCK();
    private static native int get_F_WRLCK();
    public static final int O_ACCMODE = get_O_ACCMODE();
    private static native int get_O_ACCMODE();
    public static final int O_APPEND = get_O_APPEND();
    private static native int get_O_APPEND();
    public static final int O_CREAT = get_O_CREAT();
    private static native int get_O_CREAT();
    public static final int O_EXCL = get_O_EXCL();
    private static native int get_O_EXCL();
    public static final int O_NOCTTY = get_O_NOCTTY();
    private static native int get_O_NOCTTY();
    public static final int O_NONBLOCK = get_O_NONBLOCK();
    private static native int get_O_NONBLOCK();
    public static final int O_RDONLY = get_O_RDONLY();
    private static native int get_O_RDONLY();
    public static final int O_RDWR = get_O_RDWR();
    private static native int get_O_RDWR();
    public static final int O_SYNC = get_O_SYNC();
    private static native int get_O_SYNC();
    public static final int O_TRUNC = get_O_TRUNC();
    private static native int get_O_TRUNC();
    public static final int O_WRONLY = get_O_WRONLY();
    private static native int get_O_WRONLY();
    public static final int R_OK = get_R_OK();
    private static native int get_R_OK();
    public static final int SEEK_CUR = get_SEEK_CUR();
    private static native int get_SEEK_CUR();
    public static final int SEEK_END = get_SEEK_END();
    private static native int get_SEEK_END();
    public static final int SEEK_SET = get_SEEK_SET();
    private static native int get_SEEK_SET();
    public static final int STDERR_FILENO = get_STDERR_FILENO();
    private static native int get_STDERR_FILENO();
    public static final int STDIN_FILENO = get_STDIN_FILENO();
    private static native int get_STDIN_FILENO();
    public static final int STDOUT_FILENO = get_STDOUT_FILENO();
    private static native int get_STDOUT_FILENO();
    public static final int W_OK = get_W_OK();
    private static native int get_W_OK();
    public static final int X_OK = get_X_OK();
    private static native int get_X_OK();
}
